name: Discord Push Notification

on:
  push:
    branches:
      - '**'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.Discord_Webhook }}
          REPOSITORY: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          AUTHOR: ${{ github.actor }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message || 'No commit message available' }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "🚀 Push notification",
              "embeds": [{
                "title": "Progress Achive",
                "description": "**Repository:** '"$REPOSITORY"'\n**Branch:** '"$BRANCH"'\n**Author:** '"$AUTHOR"'\n**Commit Message:** '"$COMMIT_MESSAGE"'",
                "color": 65280
              }]
            }' \
            "$DISCORD_WEBHOOK"